const liquors =
    [
        {
            name: 'Screwdriver',
            alcohols: ['Vodka'],
            mixers: ['Orange Juice'],
            image: "https://www.thecocktaildb.com/images/media/drink/8xnyke1504352207.jpg",
        },
        {
            name: 'Vodka Tonic',
            alcohols: ['Vodka'],
            mixers: ['Tonic'],
            image: "https://www.thecocktaildb.com/images/media/drink/lmj2yt1504820500.jpg",
        },
        {
            name: 'Vodka Soda',
            alcohols: ['Vodka'],
            mixers: ['Soda'],
            image: null,
        },
        {
            name: 'Vodka Cranberry',
            alcohols: ['Vodka'],
            mixers: ['Cranberry Juice'],
            image: null,
        },
        {
            name: 'Copperhead',
            alcohols: ['Vodka'],
            mixers: ['Ginger Ale'],
            image: null,
        },
        {
            name: 'Vodka and Coke',
            alcohols: ['Vodka'],
            mixers: ['Coke'],
            image: null,
        },
        {
            name: 'Vodka and Sprite',
            alcohols: ['Vodka'],
            mixers: ['Sprite'],
            image: null,
        },
        {
            name: 'Tequila Screwdriver',
            alcohols: ['Tequila'],
            mixers: ['Orange Juice'],
            image: null,
        },
        {
            name: 'Tequila Tonic',
            alcohols: ['Tequila'],
            mixers: ['Tonic'],
            image: null,
        },
        {
            name: 'Tequila Soda',
            alcohols: ['Tequila'],
            mixers: ['Soda'],
            image: null,
        },
        {
            name: 'Tequila Cranberry',
            alcohols: ['Tequila'],
            mixers: ['Cranberry Juice'],
            image: null,
        },
        {
            name: 'Tequila Ginger',
            alcohols: ['Tequila'],
            mixers: ['Ginger Ale'],
            image: null,
        },
        {
            name: 'Tequila and Coke',
            alcohols: ['Tequila'],
            mixers: ['Coke'],
            image: null,
        },
        {
            name: 'Tequila and Sprite',
            alcohols: ['Tequila'],
            mixers: ['Sprite'],
            image: null,
        },
        {
            name: 'Gin Screwdriver',
            alcohols: ['Gin'],
            mixers: ['Orange Juice'],
            image: null,
        },
        {
            name: 'Gin and Tonic',
            alcohols: ['Gin'],
            mixers: ['Tonic'],
            image: null,
        },
        {
            name: 'Gin Soda',
            alcohols: ['Gin'],
            mixers: ['Soda'],
            image: null,
        },
        {
            name: 'Gin Cranberry',
            alcohols: ['Gin'],
            mixers: ['Cranberry Juice'],
            image: null,
        },
        {
            name: 'Gin and Ginger',
            alcohols: ['Gin'],
            mixers: ['Ginger Ale'],
            image: null,
        },
        {
            name: 'Gin and Coke',
            alcohols: ['Gin'],
            mixers: ['Coke'],
            image: null,
        },
        {
            name: 'Gin and Sprite',
            alcohols: ['Gin'],
            mixers: ['Sprite'],
            image: null,
        },
        {
            name: 'Whiskey Screwdriver',
            alcohols: ['Whiskey'],
            mixers: ['Orange Juice'],
            image: null,
        },
        {
            name: 'Whiskey Tonic',
            alcohols: ['Whiskey'],
            mixers: ['Tonic'],
            image: null,
        },
        {
            name: 'Whiskey Soda',
            alcohols: ['Whiskey'],
            mixers: ['Soda'],
            image: null,
        },
        {
            name: 'Whiskey Cranberry',
            alcohols: ['Whiskey'],
            mixers: ['Cranberry Juice'],
            image: null,
        },
        {
            name: 'Whiskey Ginger',
            alcohols: ['Whiskey'],
            mixers: ['Ginger Ale'],
            image: null,
        },
        {
            name: 'Whiskey and Coke',
            alcohols: ['Whiskey'],
            mixers: ['Coke'],
            image: null,
        },
        {
            name: 'Whiskey and Sprite',
            alcohols: ['Whiskey'],
            mixers: ['Sprite'],
            image: null,
        },
        {
            name: 'Rum Screwdriver',
            alcohols: ['Rum'],
            mixers: ['Orange Juice'],
            image: null,
        },
        {
            name: 'Rum Tonic',
            alcohols: ['Rum'],
            mixers: ['Tonic'],
            image: './images/rum_tonic_thumb.jpg',
        },
        {
            name: 'Rum Soda',
            alcohols: ['Rum'],
            mixers: ['Soda'],
            image: null,
        },
        {
            name: 'Rum Cranberry',
            alcohols: ['Rum'],
            mixers: ['Cranberry Juice'],
            image: './images/rum_cranberry_thumb.jpg',
        },
        {
            name: 'Rum Ginger',
            alcohols: ['Rum'],
            mixers: ['Ginger Ale'],
            image: null,
        },
        {
            name: 'Cuba Libre',
            alcohols: ['Rum'],
            mixers: ['Coke'],
            image: './images/cuba_libre_thumb.jpg',
        },
        {
            name: 'Spritsy Cranberry Rum',
            alcohols: ['Rum'],
            mixers: ['Sprite', 'Cranberry Juice'],
            image: './images/rum_cranberry_sprite_thumb.jpg',
        },
        {
            name: 'Rum and Sprite',
            alcohols: ['Rum'],
            mixers: ['Sprite'],
            image: './images/rum_sprite_thumb.jpg',
        },
    ]

module.exports.liquors = liquors;